In [ ]:
#Machine Epsilon (기계 오차)
#아래 코드가 53이 나오는 이유 : 1/2^54 가 기계 오차보다 작기 때문
k=0
while (1+1/2**k)>1:
  k+=1
print(k)

53


In [ ]:
#Machine Epsilon 추정
#*Machine Epsilon (기계 오차) : 1+eps를 부동 소수점 시스템의 컴퓨터에서 표현 시 1+eps가 1보다 크게되는 '최소의' 양의 실수

meps=1
while 1+meps>1:
    meps = meps/2
meps = 2*meps
print(meps)

2.220446049250313e-16


In [ ]:
#단정밀도와 배정밀도
import numpy as np

#단정밀도 (single precision) 머신 입실론 : 부호 1비트, 지수 8비트, 가수 23비트로 구성. 정밀도가 그리 중요하지 않으면서 메모리 절약이 필요한 경우 사용
print(np.finfo(np.float32).eps)
#배정밀도 (double precision) 머신 입실론 : 부호 1비트, 지수 11비트, 가수 52비트로 구성. 높은 정밀도 요구하는 경우 사용
print(np.finfo(np.float64).eps)

1.1920929e-07
2.220446049250313e-16


In [ ]:
#마무리 오차의 영향
sum1 = 1.0 #1에 diff를 계속 더함
sum2= 0.0 # diff를 먼저 더한 후 1을 더함
diff = 1/10**16 #meps보다 작은 수

for i in range(10**7):
  sum1 += diff
  sum2 += diff
sum2 = 1.0 + sum2

print(sum1)
print(sum2)

1.0
1.000000001


In [ ]:
#매클로린 급수를 이용해 e^x 근사화

import math

#매클로린 급수 사용자 정의 함수
def mac (x,n):
  f=0
  for i in  range (n):
    f+=x**i/math.factorial(i)
  return f

real = math.e
approx = mac(1,3)
ocha = real - approx

print("참값 : {}".format(real))
print("근사값 : {}".format(approx))
print("절단오차 : {}".format(ocha))


참값 : 2.718281828459045
근사값 : 2.5
절단오차 : 0.2182818284590451


In [ ]:
#선형방정식 Ax=b를 푸는 방법 1 : A의 역행렬을 구하여 계산 (계산 비용이 너무 크고 수치적 불안정성을 갖기 때문에 좋은 방법은 아님)
import numpy as np
#행렬 A,b 선언
A = np.array([[-1, 1, 2], [3, -1, 1], [-1, 3, 4]], dtype=float)
b = np.array([2, 6, 4], dtype=float)


A_inv = np.linalg.inv(A) #A의 역행렬


x = np.dot(A_inv, b) #A의 역행렬과 b의 행렬곱을 이용해 x 계산 = np.dot(A_inv, b) #A의 역행렬과 b의 행렬곱을 이용해 x 계산
print(x)

[ 1. -1.  2.]


In [16]:
#가우스 소거법
#순서 : 1. A,b를 확대 행렬로 변환 후 A행렬의 위삼각행렬화 2.역진대입법 수행

import numpy as np


def naiveGauss(A,b):
  #A행렬의 위삼각행렬화
  n=len(b)
  for j in range(0,n-1):
    for i in range(j+1,n):
      factor = A[i,j]/A[j,j]
      A[i,:] = A[i,:] - A[j,:]*factor
      b[i] = b[i] - b[j]*factor
  #역진대입법
  x=np.zeros(n)
  x[n-1]=b[n-1]/A[n-1,n-1]
  for i in range(n-2,-1,-1):
    sum=0
    for k in range(i+1, n):
      sum = sum+A[i,k]*x[k]
      x[i] = (b[i] - sum) / A[i,i]
  return x



A = np.array([[-1,1,2],[3,-1,1],[-1,3,4]],dtype = float)
b= np.array([2,6,4])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv,b)

print(x)
print(naiveGauss(A,b))

[ 1. -1.  2.]
[ 1. -1.  2.]
